superlists/lists/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
]

superlists/superlists/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    url(r'^$', list_views.home_page, name="home"),
    url(r'^lists/', include(list_urls)),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = urlpatterns + [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] 

superlists/lists/models.py
from django.db import models

class List(models.Model):
    text = models.TextField(default='')


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

superlists/lists/views.py
from django.shortcuts import render, redirect
#from django.http import HttpResponse
from lists.models import Item, List

def home_page(request):
    
    lists = List.objects.all()
    return render(request, 'lists/home.html', {'lists': lists })

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
#    items = Item.objects.filter(list=list_)
    return render(request, 'lists/list.html', {'list': list_})

def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect(f'/lists/{list_.id}/')

def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect(f'/lists/{list_.id}/')

superlists/lists/templates/lists/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap3/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>

<body>
    <div class="container">
        <div class="header clearfix">

            <h3 class="text-muted">Super List</h3>
        </div>
        <div class="row">
            <div class="jumbotron">
                <div class="text-center">
                    <h1>{% block header_text %}{% endblock %}</h1>
                    <form method="POST" action="{% block form_action %}{% endblock %}">
                        <input name="item_text" id="id_new_item" class="form-control input-lg" placeholder="Enter a to-do item" /> {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {% block table %} {% endblock %}
            </div>
        </div>

    </div>
</body>

</html>

superlists/lists/templates/lists/home.html
{% extends './base.html' %}
{% block header_text %}Start a new To-Do list{% endblock %}


{% block table %}
<h2>or check existing list</h2>
{% for item in lists %}
<ul>
<ol><a href="/lists/{{ item.id }}">{{ item.id }}</a></ol>
</ul>


{% endfor %} 
{% endblock %}


{% block form_action %}/lists/new{% endblock %}

superlists/lists/templates/lists/list.html
{% extends './base.html' %}
{% block header_text %}Your To-Do list{% endblock %}
{% block form_action %}/lists/{{ list.id }}/add_item{% endblock %}

{% block table %}
<table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
    <tr>
        <td>{{ forloop.counter }}: {{ item.text }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}